import 'dart:convert';
import 'dart:io';

import 'package:file_picker/file_picker.dart';
import 'package:silo_vault/core/enums/db_enums.dart';
import 'package:silo_vault/database/vault_repository.dart';
import 'package:silo_vault/features/models/vault_item.dart';
import 'package:path_provider/path_provider.dart';

/// Handles vault data export (decrypt → JSON file) and import (JSON file → validate → encrypt → DB).
class DataTransferService {
  final VaultRepository _repo = VaultRepository();

  // ── Export ──

  /// Exports all vault items as a JSON file.
  /// Returns the file path on success, null on failure.
  Future<String?> exportToJson() async {
    final items = await _repo.getAllItems();
    if (items.isEmpty) return null;

    final jsonList = items.map((item) => _itemToMap(item)).toList();
    final payload = jsonEncode({
      'version': 1,
      'exportedAt': DateTime.now().toIso8601String(),
      'itemCount': jsonList.length,
      'items': jsonList,
    });

    final dir = await getApplicationDocumentsDirectory();
    final timestamp = DateTime.now().millisecondsSinceEpoch;
    final file = File('${dir.path}/notes_vault_backup_$timestamp.json');
    await file.writeAsString(payload);

    return file.path;
  }

  // ── Import ──

  /// Lets user pick a JSON file and imports items into the vault.
  /// Returns the count of items imported, or -1 on failure.
  Future<int> importFromJson() async {
    final result = await FilePicker.platform.pickFiles(
      type: FileType.custom,
      allowedExtensions: ['json'],
    );

    if (result == null || result.files.isEmpty) return 0;

    final filePath = result.files.single.path;
    if (filePath == null) return -1;

    final file = File(filePath);
    if (!await file.exists()) return -1;

    final content = await file.readAsString();

    try {
      final data = jsonDecode(content) as Map<String, dynamic>;
      final version = data['version'] as int?;
      if (version == null || version != 1) return -1;

      final rawItems = data['items'] as List<dynamic>?;
      if (rawItems == null || rawItems.isEmpty) return 0;

      final items = <VaultItem>[];
      for (final raw in rawItems) {
        final item = _mapToItem(raw as Map<String, dynamic>);
        if (item != null) items.add(item);
      }

      if (items.isEmpty) return 0;

      // Batch insert — each item goes through repository's encrypt path
      for (final item in items) {
        await _repo.addItem(item);
      }

      return items.length;
    } catch (_) {
      return -1;
    }
  }

  // ── Mappers ──

  Map<String, dynamic> _itemToMap(VaultItem item) {
    return {
      'id': item.id,
      'type': item.type.name,
      'title': item.title,
      'content': item.content,
      'username': item.username,
      'password': item.password,
      'websiteUrl': item.websiteUrl,
      'category': item.category.name,
      'tags': item.tags.map((t) => t.name).toList(),
      'isFavorite': item.isFavorite,
      'isTrashed': item.isTrashed,
      'passwordStrength': item.passwordStrength?.name,
      'createdAt': item.createdAt.toIso8601String(),
      'updatedAt': item.updatedAt.toIso8601String(),
    };
  }

  VaultItem? _mapToItem(Map<String, dynamic> map) {
    try {
      return VaultItem(
        id: '', // New ID will be generated by repository
        type: NoteType.values.firstWhere(
          (e) => e.name == map['type'],
          orElse: () => NoteType.note,
        ),
        title: map['title'] as String? ?? 'Untitled',
        content: map['content'] as String?,
        username: map['username'] as String?,
        password: map['password'] as String?,
        websiteUrl: map['websiteUrl'] as String?,
        category: NoteCategory.values.firstWhere(
          (e) => e.name == map['category'],
          orElse: () => NoteCategory.personal,
        ),
        tags:
            (map['tags'] as List<dynamic>?)
                ?.map(
                  (t) => ItemTag.values.firstWhere(
                    (e) => e.name == t,
                    orElse: () => ItemTag.important,
                  ),
                )
                .toList() ??
            [],
        isFavorite: map['isFavorite'] as bool? ?? false,
        isTrashed: map['isTrashed'] as bool? ?? false,
        passwordStrength: map['passwordStrength'] != null
            ? PasswordStrength.values.firstWhere(
                (e) => e.name == map['passwordStrength'],
                orElse: () => PasswordStrength.fair,
              )
            : null,
        createdAt: map['createdAt'] != null
            ? DateTime.parse(map['createdAt'] as String)
            : DateTime.now(),
        updatedAt: map['updatedAt'] != null
            ? DateTime.parse(map['updatedAt'] as String)
            : DateTime.now(),
      );
    } catch (_) {
      return null;
    }
  }
}
